"""add reset password

Revision ID: 1bec62ee126b
Revises: 5e4ce3f0d7c0
Create Date: 2020-03-11 16:19:31.986149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bec62ee126b'
down_revision = '5e4ce3f0d7c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_password',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('answer', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reset_password_answer'), 'reset_password', ['answer'], unique=False)
    op.create_index(op.f('ix_reset_password_question'), 'reset_password', ['question'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reset_password_question'), table_name='reset_password')
    op.drop_index(op.f('ix_reset_password_answer'), table_name='reset_password')
    op.drop_table('reset_password')
    # ### end Alembic commands ###
